# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
t1 = torch.rand(7, 7)
t1

tensor([[0.6826, 0.5910, 0.1355, 0.5547, 0.0029, 0.3042, 0.3555],
        [0.6978, 0.7661, 0.7187, 0.1403, 0.2952, 0.5815, 0.4162],
        [0.4592, 0.5449, 0.3447, 0.5602, 0.0644, 0.4219, 0.7492],
        [0.9684, 0.1934, 0.8917, 0.5627, 0.0241, 0.6410, 0.4508],
        [0.1901, 0.8731, 0.5229, 0.0974, 0.2825, 0.0283, 0.1895],
        [0.5050, 0.8713, 0.7383, 0.2835, 0.5180, 0.8434, 0.0077],
        [0.0380, 0.3385, 0.1550, 0.8764, 0.6180, 0.1896, 0.4442]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
t2 = torch.rand(1, 7)
t2
# Perform matrix multiplication
t3 = torch.matmul(t1, t2.T)
t3

tensor([[1.0882],
        [1.9039],
        [1.3839],
        [2.0917],
        [1.0253],
        [2.3066],
        [1.4544]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
t1 = torch.rand(7, 7)
t2 = torch.rand(1, 7)

# Matrix multiply tensors
t3 = torch.matmul(t1, t2.T)
print(t3)
print(t3.size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [33]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [32]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

# Create two random tensors on GPU
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

t1_cuda = t1.to(device)
t2_cuda = t2.to(device)

print(t1_cuda)
print(t2_cuda)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [49]:
# Perform matmul on tensor_A and tensor_B
t4 = torch.matmul(t1_cuda, t2_cuda.T)
t4

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [52]:
# Find max
print(torch.max(t4))

# Find min
print(torch.min(t4))

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [53]:
# Find arg max
print(torch.argmax(t4))

# Find arg min
print(torch.argmin(t4))

tensor(3, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [63]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_flat = torch.squeeze(tensor)

# Print out tensors and their shapes
print(tensor)
tensor.size()

print(tensor_flat)
tensor_flat.size()

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])


torch.Size([10])